spring.application.name=TallerHDD
spring.data.mongodb.uri=mongodb://localhost:27017/sansaweigh
spring.data.redis.host=localhost
spring.data.redis.port=6379

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

scale.api.base-url=http://localhost:9090